services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Psr\Container\ContainerInterface: ~

  Axxis\Bundle\StockBundle\Controller\Frontend\StockController:
    calls:
      - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
    tags:
      - { name: container.service_subscriber }

  Axxis\Bundle\StockBundle\Layout\Block\StockInfoBlockType:
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: layout.block_type, alias: axxis_stock_info }

  Axxis\Bundle\StockBundle\Command\CreateProductCommand:
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: 'console.command' }